# Generated by Django 4.1.2 on 2022-10-31 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketId",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("market_id", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name_plural": "Market IDs",
            },
        ),
        migrations.CreateModel(
            name="StoreNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("store_number", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name_plural": "Store Numbers",
            },
        ),
        migrations.CreateModel(
            name="TerminalId",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("terminal_id", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name_plural": "Terminal IDs",
            },
        ),
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("uploaded_file", models.FileField(upload_to="uploads/")),
                (
                    "converted_file",
                    models.FileField(
                        blank=True, null=True, upload_to="converted_files/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "market_id",
                    models.ForeignKey(
                        default=111111,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="market",
                        to="course.marketid",
                    ),
                ),
                (
                    "store_number",
                    models.ForeignKey(
                        default=1111,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="store",
                        to="course.storenumber",
                    ),
                ),
                (
                    "terminal_id",
                    models.ForeignKey(
                        default=111,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="terminal",
                        to="course.terminalid",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(blank=True, max_length=100)),
                ("email", models.EmailField(max_length=254)),
                (
                    "image",
                    models.ImageField(default="default.jpg", upload_to="profile_pics"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
