# Generated by Django 4.1.2 on 2022-10-31 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0004_alter_store_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="store",
            options={"verbose_name_plural": "Stores"},
        ),
        migrations.AlterField(
            model_name="store",
            name="market_id",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="course.marketid",
            ),
        ),
        migrations.AlterField(
            model_name="store",
            name="store_number",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="course.storenumber",
            ),
        ),
        migrations.AlterField(
            model_name="store",
            name="terminal_id",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="course.terminalid",
            ),
        ),
    ]
